# Ignore everything
*

# Allow these files and directories
!/deploy
!/revert
!/hyperknowledge
!/scripts
!/pyproject.toml
!/setup.cfg

# Ignore unnecessary files inside allowed directories
# This should go after the allowed directories
**/*~
**/*.log
**/.DS_Store
**/Thumbs.db