version: "3"

networks:
  my_net:

volumes:
  pgdata:

services:
  postgres:
    image: conversence/postgres:alpine-jwt-uuid7
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_net

  hyperknowledge:
    image: conversence/hyperknowledge:latest
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my_net
    ports:
      - "8000:8000"
